# Generated by Django 2.2.5 on 2019-11-14 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20190929_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='task',
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='vehicle',
            field=models.CharField(default='dfhdfhfdhrdfhrdfhrdfhdfhrsd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
