# Generated by Django 2.2.5 on 2019-11-14 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0007_auto_20191113_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='VehicleMaintenance',
        ),
    ]
