# Generated by Django 2.2.5 on 2019-11-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20191113_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
