# Generated by Django 2.2.5 on 2019-11-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20191115_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='location',
            field=models.CharField(max_length=200, null='Self'),
        ),
    ]
