# Generated by Django 2.2.5 on 2019-11-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20191115_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='mileage',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
