# Generated by Django 2.2.5 on 2019-11-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_vehiclemaintenance_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='location',
            field=models.CharField(default='blah blah blah', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
